name: Build Electron App for Windows

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-windows:
    runs-on: windows-latest  # Uses GitHub's Windows runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Match your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build -- --win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List contents of dist directory
        run: dir dist/

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/*.exe
