name: Build Electron App for macOS

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-macos:
    runs-on: macos-latest  # Uses GitHub's macOS runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Match your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run build -- --mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List contents of dist directory
        run: ls -al dist/

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: dist/*.zip
